INSERT INTO employees(name, department) VALUES('Krotov Leonid', 'Marketing');
INSERT INTO employees(name, department) VALUES('Koksharova Yuliya', 'PR');
INSERT INTO employees(name, department) VALUES('Raskoshniy Artyom', 'Support');
INSERT INTO employees(name, department) VALUES('Kirov Ivan', 'Sales');
INSERT INTO employees(name, department) VALUES('Sergeev Semen', 'Sales');
INSERT INTO employees(name, department) VALUES('Zimovik Nikita', 'Support');
INSERT INTO employees(name, department) VALUES('Mutiyanov Vyacheslav', 'Technical Service');
INSERT INTO employees(name, department) VALUES('Sumina Svetlana', 'Accounting');
INSERT INTO employees(name, department) VALUES('Tavrina Yuliya', 'HR');
INSERT INTO employees(name, department) VALUES('Bilan Andrey', 'Industrial Design');
INSERT INTO employees(name, department) VALUES('Gorbachev Vasiliy', 'Security');
INSERT INTO employees(name, department) VALUES('Tikhonov Artyom', 'Transport');
INSERT INTO employees(name, department) VALUES('Levin Alexander', 'Transport');
INSERT INTO employees(name, department) VALUES('Konovalova Svetlana', 'System administration');
INSERT INTO employees(name, department) VALUES('Nazarov Evgeniy', 'Compliance');
INSERT INTO employees(name, department) VALUES('Patimov Iliya', 'Marketing');
INSERT INTO employees(name, department) VALUES('Andreichikov Nikolai', 'Industrial Design');
INSERT INTO employees(name, department) VALUES('Barakhovskaya Elena', 'Promoter');
INSERT INTO employees(name, department) VALUES('Anikina Ekaterina', 'Promoter');
INSERT INTO employees(name, department) VALUES('Olisova Valentina', 'Design');

INSERT INTO disabled(employee_id) VALUES(5);
INSERT INTO disabled(employee_id) VALUES(10);
INSERT INTO disabled(employee_id) VALUES(11);
INSERT INTO disabled(employee_id) VALUES(15);

INSERT INTO projects(category) VALUES('City Day Advertising');
INSERT INTO projects(category) VALUES('New Banking Product Promotion amd Sales');
INSERT INTO projects(category) VALUES('Design and Production of Electricity Generation Equipment');
INSERT INTO projects(category) VALUES('Advertising and Sales of Accounting Software');

INSERT INTO employees_projects(employee_id, project_id) VALUES(1, 1);
INSERT INTO employees_projects(employee_id, project_id) VALUES(2, 1);
INSERT INTO employees_projects(employee_id, project_id) VALUES(3, 4);
INSERT INTO employees_projects(employee_id, project_id) VALUES(4, 2);
INSERT INTO employees_projects(employee_id, project_id) VALUES(5, 4);
INSERT INTO employees_projects(employee_id, project_id) VALUES(6, 2);
INSERT INTO employees_projects(employee_id, project_id) VALUES(7, 3);
INSERT INTO employees_projects(employee_id, project_id) VALUES(8, 4);
INSERT INTO employees_projects(employee_id, project_id) VALUES(9, 4);
INSERT INTO employees_projects(employee_id, project_id) VALUES(10, 3);
INSERT INTO employees_projects(employee_id, project_id) VALUES(11, 3);
INSERT INTO employees_projects(employee_id, project_id) VALUES(12, 4);
INSERT INTO employees_projects(employee_id, project_id) VALUES(13, 3);
INSERT INTO employees_projects(employee_id, project_id) VALUES(14, 4);
INSERT INTO employees_projects(employee_id, project_id) VALUES(15, 2);
INSERT INTO employees_projects(employee_id, project_id) VALUES(16, 2);
INSERT INTO employees_projects(employee_id, project_id) VALUES(17, 3);
INSERT INTO employees_projects(employee_id, project_id) VALUES(18, 1);
INSERT INTO employees_projects(employee_id, project_id) VALUES(19, 2);
INSERT INTO employees_projects(employee_id, project_id) VALUES(20, 1);
